# Generated by Django 5.1.3 on 2024-12-09 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('shortName', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('town', models.CharField(max_length=60)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('toiture', models.CharField(blank=True, choices=[('ouverte', 'Ouverte'), ('couverte', 'Couverte'), ('retractable', 'Rétractable')], max_length=30, null=True)),
                ('creation', models.DateField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('conferences', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='team.conferences')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('town', models.CharField(max_length=60)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('founded', models.DateField(default='1950-01-01')),
                ('owner', models.CharField(blank=True, max_length=60, null=True)),
                ('colorOne', models.CharField(blank=True, max_length=15, null=True)),
                ('colorTwo', models.CharField(blank=True, max_length=15, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='team.divisions')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='team.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Superbowls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('town', models.CharField(max_length=60)),
                ('stadium', models.CharField(max_length=60)),
                ('teamOne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superbowls_teamOne', to='team.teams')),
                ('teamTwo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superbowls_teamTwo', to='team.teams')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superbowls_winner', to='team.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Coachs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('firstName', models.CharField(max_length=60)),
                ('poste', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('actif', models.BooleanField()),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coachs', to='team.teams')),
            ],
        ),
    ]
