# Generated by Django 5.1.3 on 2024-11-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='founded',
            field=models.DateField(default='1950-01-01'),
        ),
        migrations.AddField(
            model_name='teams',
            name='stadium',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='PLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('firstName', models.CharField(max_length=60)),
                ('poste', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='photo')),
                ('age', models.DateField(default='1980-01-01')),
                ('actif', models.BooleanField()),
                ('injury', models.BooleanField()),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='team.teams')),
            ],
        ),
    ]
