# Generated by Django 5.1.3 on 2024-12-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Superbowls',
        ),
    ]
