# Generated by Django 5.1.3 on 2024-12-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('town', models.CharField(max_length=60)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('toiture', models.CharField(blank=True, choices=[('ouverte', 'Ouverte'), ('couverte', 'Couverte'), ('retractable', 'Rétractable')], max_length=30, null=True)),
                ('creation', models.DateField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stadium')),
            ],
        ),
        migrations.AddField(
            model_name='superbowls',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='team.stadium'),
        ),
    ]
