# Generated by Django 5.1.3 on 2024-12-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_stadium_superbowls_year_alter_teams_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
