# Generated by Django 5.1.3 on 2024-11-19 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teams_founded_teams_stadium_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='players',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/photo'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/logo'),
        ),
        migrations.CreateModel(
            name='Coachs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('firstName', models.CharField(max_length=60)),
                ('poste', models.CharField(blank=True, max_length=50, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/photo')),
                ('actif', models.BooleanField()),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coachs', to='team.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Superbowls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=60)),
                ('stadium', models.CharField(max_length=60)),
                ('teamOne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superbowls_teamOne', to='team.teams')),
                ('teamTwo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superbowls_teamTwo', to='team.teams')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superbowls_winner', to='team.teams')),
            ],
        ),
    ]
