# Generated by Django 5.1.3 on 2024-11-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_conferences_divisions_alter_players_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superbowls',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
