# Generated by Django 5.1.3 on 2024-11-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_superbowls_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisions',
            name='conferences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='team.conferences'),
        ),
        migrations.AddField(
            model_name='teams',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='team.divisions'),
        ),
    ]
