# Generated by Django 5.1.3 on 2024-11-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_divisions_conferences_teams_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachs',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='players',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
