# Generated by Django 5.1.3 on 2024-11-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_coachs_thumbnail_alter_players_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferences',
            name='shortName',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
