# Generated by Django 5.1.3 on 2024-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_conferences_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='colorOne',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='colorTwo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
