# Generated by Django 5.1.3 on 2024-11-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_teams_colorone_teams_colortwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PLayers',
        ),
    ]
