# Generated by Django 5.1.3 on 2024-12-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgames', '0001_initial'),
        ('team', '0002_delete_superbowls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='playgame',
            name='played_at',
            field=models.DateTimeField(default='2023-01-01'),
        ),
        migrations.CreateModel(
            name='Superbowls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('town', models.CharField(max_length=60)),
                ('stadium', models.CharField(max_length=60)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superbowls', to='playgames.season')),
                ('teamOne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superbowls_teamOne', to='team.teams')),
                ('teamTwo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superbowls_teamTwo', to='team.teams')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superbowls_winner', to='team.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('is_playoff', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='playgames.season')),
            ],
        ),
        migrations.AddField(
            model_name='playgame',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='playgames.week'),
        ),
    ]
