# Generated by Django 5.1.3 on 2024-12-09 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgames', '0002_season_playgame_played_at_superbowls_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgame',
            name='played_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
