# Generated by Django 5.1.3 on 2024-12-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgames', '0004_alter_playgame_score_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgame',
            name='score_local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playgame',
            name='score_visitor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
