# Generated by Django 5.1.3 on 2024-12-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgames', '0005_alter_playgame_score_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
