# Generated by Django 5.1.3 on 2024-12-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgames', '0007_alter_playgame_played_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
