# Generated by Django 5.1.3 on 2024-12-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
