# Generated by Django 5.1.3 on 2024-12-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='poste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
