# Generated by Django 5.1.3 on 2024-12-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='draft',
            field=models.DateField(blank=True, null=True),
        ),
    ]
